services:
  php:
    build:
      context: .
    ports:
      - "1234:80"
    volumes:
      - ./:/var/www/html:cached
    restart: no

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: giga_article
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
